### ISSUE TITLE
Will this work on OS X

### ISSUE THREAD

**Issue by digitalbear** [j-keck/lsleases#3]
I have installed this on Windows and it is working great.  Just checking whether there is likely to be an OS X version or whether one of the other versions will work on OS X ?  Cheers.

**Comment by j-keck** [comment]
hello, i have it never tested under osx.

you can build it yourself, if you has the go toolchain installed: https://github.com/j-keck/lsleases#installation-from-source

i have build a 64bit os-x version for you:
[lsleases-darwin-1.4.0-7-ge41a076.gz](https://github.com/j-keck/lsleases/files/133814/lsleases-darwin-1.4.0-7-ge41a076.gz)

unpack it, start it per 'lsleases -s'.

if you build a start script, feel free to open an pull-request, and i will merge it ;-)

please report back if it works
thanks,  juergen

**Comment by digitalbear** [comment]
I have never used go before but I finally got some time to look into this.  The problem on my machine (OS X 10.8.5) is that the server does not appear to be listening on port 67, so I added some debug in dhcp.go `verboseLog.Println("listening on ", con.LocalAddr().String())` and found that what is being returned from `net.ListenUDP("udp", addr)` is "[::]:67"

I explicitly set this to use udp4 and this seems to work, well, sort-of.  `net.ListenUDP("udp4", addr)` now returns "0.0.0.0:67" and the server picks up the first DHCP Request.  I have to restart it to pick up any further requests and and the client is not receiving.

**Comment by j-keck** [comment]
good start.

can you please start the server with the verbose flag?
and post the result here or send it directly to me if you don't want publish it.

    root@main:~ # lsleases -s -v
    2016/03/21 08:03:02 enable active check - ping every: 15m
    2016/03/21 08:03:02 arping '192.168.1.23' to check permission
    2016/03/21 08:03:03 check offline hosts per ping
    2016/03/21 08:03:22 new dhcp datagram received
    2016/03/21 08:03:22 process datagram with type: 'DHCP Request' - src mac: 'b8:27:eb:88:aa:5a'
    2016/03/21 08:03:22 trigger new DHCPLease event: ip='192.168.1.222',     mac='b8:27:eb:88:aa:5a', name='pi2-freebsd'
    2016/03/21 08:03:22 new dhcp datagram received
    2016/03/21 08:03:22 process datagram with type: 'DHCP Request' - src mac: 'b8:27:eb:88:aa:5a'
    2016/03/21 08:03:22 trigger new DHCPLease event: ip='192.168.1.222', mac='b8:27:eb:88:aa:5a', name='pi2-freebsd'
    2016/03/21 08:03:22 new DHCP Lease: '192.168.1.222   b8:27:eb:88:aa:5a pi2-freebsd'


thanks

**Comment by digitalbear** [comment]
Here is the output (after changing to udp4)

`MacBook-Air:bin root# ./lsleases -s -v
2016/03/21 20:10:45 startup -  version:  1.4.0-7-ge41a076
2016/03/21 20:10:45 listening on  0.0.0.0:67
2016/03/21 20:10:45 enable active check - ping every: 15m
2016/03/21 20:10:45 arping 'fe80::1' to check permission
2016/03/21 20:12:37 new dhcp datagram received
2016/03/21 20:12:37 ignore datagram with type: 'DHCP Discover' - src mac: 'xx:xx:xx:xx:xx:xx'
2016/03/21 20:12:37 new dhcp datagram received
2016/03/21 20:12:37 process datagram with type: 'DHCP Request' - src mac: 'xx:xx:xx:xx:xx:xx'
2016/03/21 20:12:37 trigger new DHCPLease event: ip='192.168.0.4', mac='xx:xx:xx:xx:xx:xx', name='android-xxxxxxxxxxxxxxxx'`

**Comment by j-keck** [comment]
interesting  - i'm not sure what's going on.

lsleases runs with multiple goroutines  (something like multiple threads).
the communication between the goroutines happens over channels (something like a message queue).

the function 'dhcpListener' in 'dhcp.go' is one goroutine, and listen on the network for dhcp requests. if it receives a request, it publish it over a the 'dhcpLeaseChan' channel:

    verboseLog.Printf("trigger new DHCPLease event: ip='%s', mac='%s', name='%s'", lease.IP, lease.Mac, lease.Name)
    dhcpLeaseChan <- lease  // <- HERE IS THE EVENT PUBLISHING OVER A CHANNEL

so in your log, we see that the 'dhcpListener' goroutine receives a dhcp request,
and publish's the event in the 'dhcpLeaseChan' channel.

    2016/03/21 20:12:37 trigger new DHCPLease event: ip='192.168.0.4', mac='xx:xx:xx:xx:xx:xx', name='android-xxxxxxxxxxxxxxxx'


the goroutine 'server' in 'server.go' wait's for new event's and handels it.

     case l := <-dhcpLeaseChan: // <- HERE IS THE EVENT RECEIVER FOR NEW LEASES
      // update expire entry
      if *expireBasedFlag {
        l.Expire = time.Now().Add(leaseExpiredDuration)
      }

      log.Printf("new DHCP Lease: '%s'\n", l.String())
      leases.UpdateOrAdd(l)

in your log, we don't see the 'new DHCP Lease: ....' message, so the server don't
receives the event. but why???


first step - we check if the server react on a different event:
when the lsleases server process run's, execute the client per 'lsleases -V':

    main% lsleases -V
    client: 1.4.0-6-gf729be4, server: 1.4.0-6-gf729be4

this print's the client version and ask's the server for his version. in the server,
it's handled in the same 'message handling' block.

if your output is something like:

    main% lsleases -V
    client: 1.4.0-6-gf729be4, server:

than the server doesn't handles any message.


thanks

**Comment by digitalbear** [comment]
Looks like the server is not receiving any messages.  When I run `lsleases -V` I get no output at all (when the server is running).  When server is not running, I get `client: 1.4.0-7-ge41a076, server:`

I spent the evening trying to debug using [godebug](https://github.com/mailgun/godebug) - which seems quite good, but I'm still trying to get my head around goroutines and channels, so not exactly sure what I'm looking at.

Thanks for your help.

**Comment by j-keck** [comment]
ok, we are on the right way!

can you please start the server with the '-p' flag:

    lsleases -s -v -p


thanks

**Comment by digitalbear** [comment]
MacBook-Air:bin root# ./lsleases -s -v -p
2016/03/24 20:08:05 startup -  version:  1.4.0-7-ge41a076
2016/03/24 20:08:05 listening on  0.0.0.0:67
2016/03/24 20:08:05 enable expired based - check timer: 15m0s, expire duation: 168h0m0s
2016/03/24 20:08:05 check expired leases
2016/03/24 20:09:44 new dhcp datagram received
2016/03/24 20:09:44 ignore datagram with type: 'DHCP Discover' - src mac: 'xx:xx:xx:xx:xx:xx'
2016/03/24 20:09:44 new dhcp datagram received
2016/03/24 20:09:44 process datagram with type: 'DHCP Request' - src mac: 'xx:xx:xx:xx:xx:xx'
2016/03/24 20:09:44 trigger new DHCPLease event: ip='192.168.0.4', mac='xx:xx:xx:xx:xx:xx', name='android-xxxxxxxxxxxxxxxx'
2016/03/24 20:09:44 new DHCP Lease: '192.168.0.4     xx:xx:xx:xx:xx:xx android-xxxxxxxxxxxxxxxx'

**Comment by j-keck** [comment]
it looks like it works now - doesn't it?

now we see in your log the line 'new DHCP Lease: '192.168.0.4 ....'
this log line is from the server  - so the server now receives the event.

can you please make a fresh checkout, and recompile for testing?
**!! this overrides all your local changes !!**

    git fetch origin && git reset --hard origin/master
    go build -ldflags "-X main.VERSION=$(git describe)"
    sudo ./lsleases -s -v -p


thanks for your time to debug this!

**Comment by digitalbear** [comment]
That seems to be working perfectly now.  In active and in passive modes.  Thanks!

Let me know if you need anything else.

**Comment by j-keck** [comment]
i have created a zip package for osx.
can you please check if it work's under osx?

https://github.com/j-keck/lsleases/releases/tag/1.4.1


thanks

**Comment by digitalbear** [comment]
Hi,

I have tried out the amd64 version for os x, as well as all the new shell scripts provided, and all seems to be working nicely.

Thanks

**Comment by j-keck** [comment]
hey,

thanks for your time!
