### ISSUE TITLE
Proposal: Please start using Semantic Versioning

### ISSUE THREAD

**Issue by KateGo520** [j-keck/lsleases#4]
I found that this project already [supports Go modules](https://github.com/j-keck/lsleases/blob/2.1.0/go.mod). But sadly, the [tags](https://github.com https://github.com/j-keck/lsleases/tags) doesn't follow [Semantic Versioning](https://semver.org), which means that all tags of this project will be ignored by Go modules and replaced by pseudo-versions, go get acts weirdly when tags are not in that form. It would be great to have the tagged release be named in the format vX.X.X format so that go mod can read it. 
```
	github.com/j-keck/lsleases v0.0.0-20191121073906-1d417cebcd73
```
Else the mod file shows something like `github.com/j-keck/lsleases v0.0.0-20191121073906-1d417cebcd73` which is not very readable and difficult to upgrade. It’s hard to verify which version is in use. This is not conducive to version control.

So, I propose this project to follow Semantic Versioning in future versions. For example, `v1.0.1`, `v2.0.0`, `v3.1.0-alpha`, `v3.1.0-beta.2`etc, so that other project can use tag in go.mod.

**Comment by KateGo520** [comment]
@j-keck  Could you help me review this issue? Thx :p

**Comment by j-keck** [comment]
Hello  KateGo520,

thanks for your report. I just pushed a new tag: v2.1.1.
